openapi: "3.0.0"
info:
  title: Employee Data
  version: 0.0.1
paths:
  /:
    get:
      operationId: listTables
      summary: List tables in employee database
      responses:
        "200":
          description: |-
            200 response
          content:
            application/json:
              examples:
                foo:
                  value:
                    {
                      "versions":
                        [
                          {
                            "status": "CURRENT",
                            "updated": "2011-01-21T11:33:21Z",
                            "id": "v2.0",
                            "links":
                              [
                                {
                                  "href": "http://127.0.0.1:8774/v2/",
                                  "rel": "self",
                                },
                              ],
                          },
                          {
                            "status": "EXPERIMENTAL",
                            "updated": "2013-07-23T11:33:21Z",
                            "id": "v3.0",
                            "links":
                              [
                                {
                                  "href": "http://127.0.0.1:8774/v3/",
                                  "rel": "self",
                                },
                              ],
                          },
                        ],
                    }
         
  /v2:
    get:
      operationId: getVersionDetailsv2
      summary: Show API version details
      responses:
        "200":
          description: |-
            200 response
          content:
            application/json:
              examples:
                foo:
                  value:
                    {
                      "version":
                        {
                          "status": "CURRENT",
                          "updated": "2011-01-21T11:33:21Z",
                          "media-types":
                            [
                              {
                                "base": "application/xml",
                                "type": "application/vnd.openstack.compute+xml;version=2",
                              },
                              {
                                "base": "application/json",
                                "type": "application/vnd.openstack.compute+json;version=2",
                              },
                            ],
                          "id": "v2.0",
                          "links":
                            [
                              {
                                "href": "http://127.0.0.1:8774/v2/",
                                "rel": "self",
                              },
                              {
                                "href": "http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf",
                                "type": "application/pdf",
                                "rel": "describedby",
                              },
                              {
                                "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                                "type": "application/vnd.sun.wadl+xml",
                                "rel": "describedby",
                              },
                              {
                                "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                                "type": "application/vnd.sun.wadl+xml",
                                "rel": "describedby",
                              },
                            ],
                        },
                    },
                  
                

        "203":
          description: |-
            203 response
          content:
            application/json:
              examples:
                foo:
                  value:
                    {
                      "version":
                        {
                        "birth_date": "1953-04-21",
                        "emp_no": 10100,
                        "first_name": "Hironobu",
                        "gender": "F",
                        "hire_date": "1987-09-21",
                        "last_name": "Haraldson"
                       }
                    }
